# Generated by Django 4.2.4 on 2023-12-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('num', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'shopping_car',
            },
        ),
    ]
