# Generated by Django 4.2.4 on 2024-01-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='JdBook',
            fields=[
                ('year', models.IntegerField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, db_column='Rank', null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('pinglun', models.CharField(blank=True, max_length=63, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('chuban', models.CharField(blank=True, max_length=255, null=True)),
                ('jiage', models.CharField(blank=True, max_length=63, null=True)),
                ('yuanjia', models.CharField(blank=True, max_length=63, null=True)),
                ('discount', models.CharField(blank=True, max_length=63, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'jd_book',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='JdCart',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField(blank=True, db_column='userID', null=True)),
            ],
            options={
                'db_table': 'jd_cart',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='JdCartDetail',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('cartid', models.IntegerField(blank=True, db_column='cartID', null=True)),
                ('productid', models.IntegerField(blank=True, db_column='productID', null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jd_cart_detail',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='JdProduct',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(blank=True, max_length=64, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('pic', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'jd_product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='JdUser',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(blank=True, max_length=32, null=True)),
                ('upwd', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'jd_user',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
