# Generated by Django 4.2.4 on 2024-01-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_jdcart_delete_jdcartdetail_delete_jdproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='jdbook',
            name='picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
