# Generated by Django 4.2.4 on 2024-01-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_jdbook_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
