# Generated by Django 4.2.4 on 2024-01-02 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_shop_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
