# Generated by Django 4.2.4 on 2024-01-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_shop_uname'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(blank=True, max_length=255, null=True)),
                ('bookname', models.CharField(max_length=100)),
                ('price', models.CharField(blank=True, max_length=63, null=True)),
                ('num', models.PositiveSmallIntegerField()),
                ('uname', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'history',
            },
        ),
    ]
